name: bicap-frontend-only

services:
  web-shipping:
    build:
      context: ./frontend/web-shipping
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost/api
      PORT: "3003"
    restart: unless-stopped

  web-public:
    build:
      context: ./frontend/web-public
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost/api
      PORT: "3004"
    restart: unless-stopped
