/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FarmTrace__factory } from "./FarmTrace__factory";
export { ProductCertification__factory } from "./ProductCertification__factory";
