/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace FarmTrace {
  export type UpdateEntryStruct = { data: string; timestamp: BigNumberish };

  export type UpdateEntryStructOutput = [data: string, timestamp: bigint] & {
    data: string;
    timestamp: bigint;
  };

  export type SeasonRecordStruct = {
    seasonId: string;
    farmId: string;
    initialData: string;
    createdAt: BigNumberish;
    updateHistory: FarmTrace.UpdateEntryStruct[];
  };

  export type SeasonRecordStructOutput = [
    seasonId: string,
    farmId: string,
    initialData: string,
    createdAt: bigint,
    updateHistory: FarmTrace.UpdateEntryStructOutput[]
  ] & {
    seasonId: string;
    farmId: string;
    initialData: string;
    createdAt: bigint;
    updateHistory: FarmTrace.UpdateEntryStructOutput[];
  };
}

export interface FarmTraceInterface extends Interface {
  getFunction(
    nameOrSignature: "createSeason" | "getSeason" | "seasons" | "updateSeason"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "SeasonCreated" | "SeasonUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createSeason",
    values: [string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "getSeason", values: [string]): string;
  encodeFunctionData(functionFragment: "seasons", values: [string]): string;
  encodeFunctionData(
    functionFragment: "updateSeason",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "createSeason",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSeason", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "seasons", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateSeason",
    data: BytesLike
  ): Result;
}

export namespace SeasonCreatedEvent {
  export type InputTuple = [seasonId: string, farmId: string];
  export type OutputTuple = [seasonId: string, farmId: string];
  export interface OutputObject {
    seasonId: string;
    farmId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SeasonUpdatedEvent {
  export type InputTuple = [seasonId: string, data: string];
  export type OutputTuple = [seasonId: string, data: string];
  export interface OutputObject {
    seasonId: string;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FarmTrace extends BaseContract {
  connect(runner?: ContractRunner | null): FarmTrace;
  waitForDeployment(): Promise<this>;

  interface: FarmTraceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createSeason: TypedContractMethod<
    [_seasonId: string, _farmId: string, _initialData: string],
    [void],
    "nonpayable"
  >;

  getSeason: TypedContractMethod<
    [_seasonId: string],
    [FarmTrace.SeasonRecordStructOutput],
    "view"
  >;

  seasons: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint] & {
        seasonId: string;
        farmId: string;
        initialData: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  updateSeason: TypedContractMethod<
    [_seasonId: string, _data: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createSeason"
  ): TypedContractMethod<
    [_seasonId: string, _farmId: string, _initialData: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getSeason"
  ): TypedContractMethod<
    [_seasonId: string],
    [FarmTrace.SeasonRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "seasons"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint] & {
        seasonId: string;
        farmId: string;
        initialData: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateSeason"
  ): TypedContractMethod<
    [_seasonId: string, _data: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "SeasonCreated"
  ): TypedContractEvent<
    SeasonCreatedEvent.InputTuple,
    SeasonCreatedEvent.OutputTuple,
    SeasonCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SeasonUpdated"
  ): TypedContractEvent<
    SeasonUpdatedEvent.InputTuple,
    SeasonUpdatedEvent.OutputTuple,
    SeasonUpdatedEvent.OutputObject
  >;

  filters: {
    "SeasonCreated(string,string)": TypedContractEvent<
      SeasonCreatedEvent.InputTuple,
      SeasonCreatedEvent.OutputTuple,
      SeasonCreatedEvent.OutputObject
    >;
    SeasonCreated: TypedContractEvent<
      SeasonCreatedEvent.InputTuple,
      SeasonCreatedEvent.OutputTuple,
      SeasonCreatedEvent.OutputObject
    >;

    "SeasonUpdated(string,string)": TypedContractEvent<
      SeasonUpdatedEvent.InputTuple,
      SeasonUpdatedEvent.OutputTuple,
      SeasonUpdatedEvent.OutputObject
    >;
    SeasonUpdated: TypedContractEvent<
      SeasonUpdatedEvent.InputTuple,
      SeasonUpdatedEvent.OutputTuple,
      SeasonUpdatedEvent.OutputObject
    >;
  };
}
