/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ProductCertificationInterface extends Interface {
  getFunction(
    nameOrSignature: "certifications" | "certifyExport" | "verifyCertification"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Certified"): EventFragment;

  encodeFunctionData(
    functionFragment: "certifications",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "certifyExport",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCertification",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "certifications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "certifyExport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCertification",
    data: BytesLike
  ): Result;
}

export namespace CertifiedEvent {
  export type InputTuple = [seasonId: string, certData: string];
  export type OutputTuple = [seasonId: string, certData: string];
  export interface OutputObject {
    seasonId: string;
    certData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProductCertification extends BaseContract {
  connect(runner?: ContractRunner | null): ProductCertification;
  waitForDeployment(): Promise<this>;

  interface: ProductCertificationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  certifications: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean] & {
        seasonId: string;
        certData: string;
        certifiedAt: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;

  certifyExport: TypedContractMethod<
    [_seasonId: string, _certData: string],
    [void],
    "nonpayable"
  >;

  verifyCertification: TypedContractMethod<
    [_seasonId: string],
    [[boolean, string]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "certifications"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean] & {
        seasonId: string;
        certData: string;
        certifiedAt: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "certifyExport"
  ): TypedContractMethod<
    [_seasonId: string, _certData: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyCertification"
  ): TypedContractMethod<[_seasonId: string], [[boolean, string]], "view">;

  getEvent(
    key: "Certified"
  ): TypedContractEvent<
    CertifiedEvent.InputTuple,
    CertifiedEvent.OutputTuple,
    CertifiedEvent.OutputObject
  >;

  filters: {
    "Certified(string,string)": TypedContractEvent<
      CertifiedEvent.InputTuple,
      CertifiedEvent.OutputTuple,
      CertifiedEvent.OutputObject
    >;
    Certified: TypedContractEvent<
      CertifiedEvent.InputTuple,
      CertifiedEvent.OutputTuple,
      CertifiedEvent.OutputObject
    >;
  };
}
