ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
packages:
  - 'web-admin'
  - 'packages/*' # Nếu api-client nằm trong thư mục packages
  - 'shared/*'   # Hoặc bất cứ đâu bạn đặt gói @bicap/api-client